### ISSUE TITLE
Consider text-based transport encoding

### ISSUE THREAD

**Issue by Razumain** [ehn-digital-green-development/hcert-spec#19]
Wouldn't the specification be more complete if a text based trasport encoding would be specified suitable for cut and paste operations and for trasport in text based applications such as e-mail, SMS, chats or similar?

Even if this is not the typical use, I would not completely rule out certain situations where a person is asked to provide a text-representation, e.g. through remote interaction with a help-desk.

Simple Base64 encoding of the binary data would probably suffice.

**Comment by jschlyter** [comment]
Will not the apps normal transport encoding take care of this? I can send binary files in both email and chat nowadays. We could define a MIME media type though.

**Comment by Razumain** [comment]
I may be totally wrong, but I envision that a person on a checking website, or in a help desk situation would benefit if the app had a "copy" alternative that copied the hcert to the clipboard in text format. The person could then choose to paste that into a chat, a window of a checkin page, SMS, e-mail or similar that does not involve showing a 2d QR code. Wouldn't it help if there was a common text-based representation in such cases?

**Comment by jschlyter** [comment]
How would the end user get this representation from, e.g., the mobile phone wallet (iOS Wallet)?

**Comment by Razumain** [comment]
> How would the end user get this representation from, e.g., the mobile phone wallet (iOS Wallet)?

Probably not. But perhaps the national health app where you apply for the hcert would.

Honestly I don't know. This issue is much more of a question to those who do know, rather than a hard request.

**Comment by fredriklj** [comment]
I think we have already defined two transport formats (raw and QR) which can be used for this. If we had the time, we could have defined how it could be "beamed" using BLE or "tapped" using NFC, but we don't. And we have to publish this version today.
