### ISSUE TITLE
Country code in issuer-claim

### ISSUE THREAD

**Issue by martin-lindstrom** [ehn-digital-green-development/hcert-spec#26]
The specification should be clear on the ISO 3166 requirement for the country code in the issuer claim. My suggestion is ISO 3166-1 alpha-2. If you need to match this country code against the C RDN of a certificate the two-letter variant is necessary.

**Comment by jschlyter** [comment]
Fixed in 41b21311a6957a7d57cab674f08023eb47acaac1
