### ISSUE TITLE
V1 final: KID

### ISSUE THREAD

**Issue by asitplus-pteufl** [ehn-digital-green-development/hcert-spec#32]
Currently the spec. says the following about the KID:
_The Key Identifier is not a security-critical field. For this reason, it MAY also be placed in an unprotected header if required. Verifiers MUST accept both options._

Why do we need to have two variants? Would it be enough to have one dedicated place?

**Comment by jschlyter** [comment]
Where the `kid` parameter may be put is specified by COSE, RFC 8152, and is explicitly allowed in both the unprotected and protected headers. Since we believe that implementors will use a generic COSE library to parse the CWTs, falling back to standard COSE semantics reasonable.

**Comment by asitplus-pteufl** [comment]
@jschlyter thx, thats clear, however unfortunately we are not there yet to have working COSE libs, e.g. for SWIFT we had to do this by hand (CBOR was not ready either, there are four libs but all had different problems). If we need it due to the COSE standard, than its fine, but then we would need to make sure to have testsets for the different KID versions. This would be good practice anyways, however due to the probably need to improvise on COSE libs, we need to be more careful.

**Comment by jschlyter** [comment]
I agree, we test vectors produce such test vectors. Tracking this via https://github.com/ehn-digital-green-development/hcert-testdata/issues/10.

**Comment by dirkx** [comment]
> Where the kid parameter may be put is specified by COSE, RFC 8152, and is explicitly allowed in both the unprotected and protected headers. Since we believe that implementors will use a generic COSE library to parse the CWTs, falling back to standard COSE semantics reasonable


I have put this in fallback in all code where I spotted it was missing - with the protected one always 'winning' from the unprotected if they would both be set.

Dw.
