### ISSUE TITLE
Recommended sizes

### ISSUE THREAD

**Issue by dirkx** [ehn-digital-green-development/hcert-spec#6]
Recommended sizes for paper Qr not quite clear yet.

**Comment by jschlyter** [comment]
Closed by 1d4b7ab402c630f6dc1b9de9765eb8f81b9737b6

**Comment by dirkx** [comment]
I'd like to re-open this.

As said to Fredrik - we're seeing good result with formats similar as those used in Germany - around 80mm for the paper version when used with consumer printers (and in the rain, etc).

**Comment by fredriklj** [comment]
I am reopening this issue as it is something we have on the list of tasks, to provide clear recommendations. This is what I have previously written for the public transport application:

https://samtrafiken.atlassian.net/wiki/spaces/BOB/pages/28999786/Considerations+for+low-resolution+printing+of+Aztec+codes

What we have as a practical experience from too large optical codes was a train company who gave out "print at home" commuter tickets. It was something like 80 mm diagonally, and some travellers laminated the optical code which made the paper reflect ambient light in the trains, making them really hard to read.

There is definitely an upper limit, and it is likely to differ between reading using a general purpose smart phone and specialised readers. Readers often have their own build-in lights to illuminate the code but a fixed lens. Smartphones these days have autofocus but the lights is likely to cause more harm than good.

So we need to find (or even guess) a sweet spot. If I would have to guess, I think that sweet spot is somewhere around 40-50 mm diagonally.
