### ISSUE TITLE
Integrate with IATA Travel Pass

### ISSUE THREAD

**Issue by M3kH** [ehn-digital-green-development/hcert-spec#62]
IATA is currently working on alternative framework that would allow Airlines to read and validate Medical informations on the same specs that Digital Green Certificate would deliver.

At the current stage seems that IATA would provide an End two End application and an integration option for Airlines to favor seamless experience.

More information can be found here: https://www.iata.org/en/programs/passenger/travel-pass/

At the time of writing some airlines seems already to have start the integration process but Technical Specifications seems to don't be publicly available.

**Comment by fredriklj** [comment]
It would be of great benefit if IATA could adopt the hcert spec for their travel passes, and simply use another claim key under (-260) for whatever payload they have drafted for those test results. That would be a first step for interoperable passes.
