### ISSUE TITLE
Specifications link in readme is broken

### ISSUE THREAD

**Issue by codebyalokgupta** [ehn-digital-green-development/hcert-spec#63]
on the page https://github.com/ehn-digital-green-development/hcert-spec under specifications thee link given as below is. broken - https://github.com/ehn-digital-green-development/hcert-spec/blob/v105/hcert_spec.md

It could be for main branch - https://github.com/ehn-digital-green-development/hcert-spec/blob/main/hcert_spec.md

**Comment by jschlyter** [comment]
Please check https://github.com/ehn-digital-green-development/hcert-spec/tree/next, next pending release

**Comment by marado** [comment]
This seems to be a duplicate of #53 .
