### ISSUE TITLE
Repository with test QR and corresponding public keys

### ISSUE THREAD

**Issue by jeroentrappers** [ehn-digital-green-development/hcert-spec#74]
For testing purposes we propose to create a repository where each member state can put examples of their generated QR codes with the corresponding keys. This way we can easily test and validate that we can interprete each of these codes correctly in our application.

Who can set this up?

**Comment by asitplus-pteufl** [comment]
This is exactly what TSI is doing right now: https://github.com/eu-digital-green-certificates/dgc-testdata each state can upload the qr codes there, also there are going to be common test cases and a test format for all codes.

**Comment by jeroentrappers** [comment]
Perfect! Thanks!
