### ISSUE TITLE
Best way to report security issues?

### ISSUE THREAD

**Issue by oc-ja** [ehn-digital-green-development/hcert-spec#81]
Hello everyone,

if I have found a security risk, which I think would be best addressed at the specification/requirements-level, whom should I contact and how?

I should note, that I'm not part of any development team currently implementing the specification, so I don't have any internal contacts.

Thank you!

Regards,

Jan

**Comment by jschlyter** [comment]
Please email me, jakob(at)kirei.se

**Comment by chris2286266** [comment]
Hello Jan,

maybe you enlighten us all and use this channel to tell us about your findings.

THX

**Comment by jschlyter** [comment]
I will create an issue once analyzed.

**Comment by asitplus-pteufl** [comment]
@oc-ja can you send the information to peter.teufl(at)a-sit.at as well, if this is urgent, we need to analyze this as well, all the things are going into final tests/production (AT) anything related to security would need to be known ASAP. Thx
